name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 3.1.5
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils: 
    git:
      url: https://github.com/in4matic-srl/esc_pos_utils
  escposprinter:
    git: https://github.com/bailabs/esc-pos-printer-flutter
  # esc_pos_utils:
    # path: ../esc_pos_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
